### ISSUE TITLE
Application algorithm

### ISSUE THREAD

**Issue by Jaycee0602** [csheaff/pa-tomography-xu-wang#3]
Hello, I saw the algorithm "Universal back-projection algorithm for photoacoustic computed tomography" in a document, and then fortunately saw your code. But I can only do some simple modifications in it. Here is an article that uses this algorithm. I got the A-line signal mentioned in it. I want to ask you how to use the data obtained by the experiment and then use it. This algorithm finally produces an image. I am looking forward to hearing from you. Thank you.
[Non-contact Photoacoustic Tomography with a Laser Doppler Vibrometer.pdf](https://github.com/csheaff/pa-tomography-xu-wang/files/3130431/Non-contact.Photoacoustic.Tomography.with.a.Laser.Doppler.Vibrometer.pdf)

**Comment by csheaff** [comment]
An issue here is that the reconstruction algorithm in this repository is intended for a planar array, not a rotational PAT system as in your paper. My first thought is that one could restructure the looping over the detector position to account for a non-planar geometry.

You could add the subdetector scheme if you liked. You might want to check the paper to make sure that the formula for the reconstruction does not assume any sort of dependence on a planar array. I don't think it does, but it would be good to double check.

If you manage to get this working, it would be great to add it to this repository. Please consider submitting a pull request if you are successful.
